### ISSUE TITLE
Make the API Available System Wide

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-Platform-2#21]
There are a few scripts that have to be in the /home/vagrant/api directory solely so they can run ```import api```. For example, `run_tests.sh`, `api_manager.py`.

It would be nice to package our API as a library such that it could be installed system wide. It should be simple enough to create a setup.py and make it pip compatible. In which case devploy would update the system package with the current code before starting the API. There is also the more flaky option of copying the module directly into `/usr/local/lib/python3.4/dist-packages/`.

Then we could add these accessory scripts to the vagrant user's path and simplify the documentation.

**Comment by jburket** [comment]
I was in a similar position on another project I as working on where I had a bunch of external scripts I wanted to use with the main code and we played around with a number of solutions, including symlinking the code into dist-packages (which in hindsight was a little questionable). Ultimately the thing that worked out the best was extending PYTHONPATH to include the directory with the code that I wanted to reference. Then I added my script directory to PATH and everything worked great.

I think this might make sense as a solution in this case as well. Since the picoCTF Platform requires an entire specific ecosystem that would have to be installed separately, it seems like making it a pip library might be a bit larger of a step than necessary. My guess is that modifying the PYTHONPATH and perhaps renaming the api folder to be more descriptive for imports (maybe something like 'pico') would get the job done the simplest way.

**Comment by cganas** [comment]
Yeah, that sounds like a good idea. It does increase the complexity of moving the API out of vagrant and onto bare metal. But that's already a hassle.

I think it would then be worth renaming/moving api_manger.py, daemon_manager.py, gunicorn_start.sh, profile.py, run.py, and run_tests.sh to the PATH. And possibly out of that directory and into a new one.

The general idea is to cleanup the api directory. And as you mentioned, we could rename the ./api/api to ./api/pico or ./api/ctf if we want to move away from branding. All of which would be an improvement.

**Comment by royragsdale** [comment]
Closed as a legacy enhancement and development shifting to [picoCTF-platform}(https://github.com/picoCTF/picoCTF-platform).

In [picoCTF-web](https://github.com/picoCTF/picoCTF-web) the api is now a setup-tools installable module.
