### ISSUE TITLE
Invalid Argument Error During Problem Addition 

### ISSUE THREAD

**Issue by nanductf** [picoCTF/picoCTF-Platform-2#25]
Problem addition - unable to add problems and errors out with grader error. 
E.g. python3 ./api_manager.py -v problems load /home/vagrant/example_problems/crypto/sdrawkcab/ graders/ static/
Error : OSError: [Errno 22] Invalid argument: 'graders/.'

Need your guidance on the best way to add problems 

Note : Test environment is Ubuntu 14.04 with defaults built based on vagrant_setup and able to get all other screens

**Comment by cganas** [comment]
Can you confirm that the directory actually exists in the vagrant environment? I don't believe the vagrantfile is syncing that folder by default (which it probably should.)

**Comment by nanductf** [comment]
Positive. All the supplied directories for arguments do exist in the test environment. 

Second point is , the test environment was built manually and not through vagrant for practical reasons to avoid a vm inside the test vm. For example Ubuntu was installed and updated and then vagrant_setup script ran successfully only for the dependencies. Platform files are extracted and kept in /home/vagrant with all folders intact and in the same hierarchy.devploy creates the nginx directory and serves it from /srv/http/ctf and all other pages rendered properly. api runs in port#8000 and nginx successfully serves the front end through port#80  and is able to connect with api. User addition and logins do happen with no issues.

**Comment by jburket** [comment]
@nanductf I was able to replicate your error. Ultimately the problem arises from loading an *individual* problem, rather than the whole problem directory (i.e. /example_problems/crypto/sdrawkcab/ vs. /example_problems). The goal of the problem loader is to load all problems in a problem directory, and it uses the path from the root of the problem directory to the problem itself to decide how the problem should be deployed. 

For example, if you load /example_problems and there is a problem in /example_problems/crypto/sdrawkcab/, then the "deploy path" for the problem in the graders and static folder will be /crypto/sdrawkcab/. When you load the problem folder directly, this "deploy path" becomes ".", which is what triggers the error. Admittedly this is a rather confusing mechanism and we should either improve it, better document it, or at least give better error messages. For now, however, you should be able to work around this issue by only ever loading the root problem directory (/example_problems). 

On a side note, there is no special meaning behind the actual name of the problems directory. You can feel free to rename that folder to anything you like. On the other hand, the name 'graders' must be preserved. The 'problem_static' folder can be renamed, but this change must be reflected in the /scripts/devploy file. We will improve documentation on this aspect in the near future as well.

**Comment by jburket** [comment]
@cganas This directory issue has been a problem on several occasions, and is one that I claim full responsibility for causing. One way we might make this easier would be to get rid of the command line arguments in the 'problems load' and instead define the 'static', 'problems', and 'graders' folders as configuration options in config.py. I'm not sure how we would expose the 'static' directory to the devploy shell script in this case, however. What do you think?

**Comment by nanductf** [comment]
@jburket Thanks it helped . I was under the impression individual problems can be added as well and hence i was trying at specific problem folder and not the root problem.

**Comment by GroundPound** [comment]
We're glad we could help. I'm keeping this issue open until we figure out the best way to prevent others from running into the same issue.

**Comment by cganas** [comment]
@jburket @GroundPound  Yeah, it has become a bit of a pain point. I think moving those options, which have completely reasonable defaults, to the config file would be effective. I'd argue that there would be two reasonable ways to expose the items.

We made a decision when creating config.py that we should keep variable defaults in their respective API, e.g. max users on a team is defined at api.team.max_team_users. I'm not sure that was the right decision. If we were to isolate the config from the api we could simply, but messily, `static_dir=$(python3 -c "import api; print(api.config.static_directory)")` when needed.

The other option would be to convert the configuration file into a json object. config.py would then serve to deserialize it and set the values where appropriate in the API.

I personally prefer the first option. I think having the config isolated from the API would allow us to expose the configuration to any auxiliary tools we end up making.

**Comment by GroundPound** [comment]
@jburket and I discussed this. The plan is to define `static`, `problems`, and `graders` in `config.py` and we'll either rewrite `devploy` in Python or reference the appropriate folder using a call out to Python as @cganas suggested. We are closing this issue and opening a new one for these changes.
