### ISSUE TITLE
Separate Competition Specific Data from Problem JSONs

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-Platform-2#27]
Moving forward with a generalized platform, and an increasing set of problems, it would be great to remove competition specific data such as the weightmap, score?, and threshold from the problem.json itself. If I were to include a subset of the pico problems in my own competition, I would have to ensure I remove all of the problems I did not include from the respective weightmaps or the api_manager will get very upset.

I would argue that we could either include this information in its own competition.json or as part of config.py.
I am unsure that it is worth having two "configuration" files. The problem score might be fine to keep as a default value.

An easy and very effective way of implementing this would allow the config.py to arbitrarily update existing fields in  the problem definitions. This adds some minor complexity to a problem linter #13.

I could imagine:

problem.json
```
{"name": "sdrawkcaB",
 "score": 10,
 "category": "Cryptography",
 "grader": "crypto/sdrawkcab/grader.py",
 "description": "Can you decipher <a target=_blank href='/problem-static/crypto/sdrawkcab/code.txt'>this secret message</a>?",
 "threshold": 0,
 "weightmap": {},
 "hint": "Maybe you should get a mirror."}
```

and maybe something like this in the config.py

```python
problems["sdrawkcaB"] = {
  "score": 40,
  "threshold": 3,
  "weightmap": {
    "cyborg secrets": 2,
    "basic-asm": 1
  }
}
```

It may make more sense to the user to expose it as a function. However, we would have to make note that it should only be called from the config.py. I'm sure there is some spooky way to do this in python and raise an exception.

```python
api.competition.configure_problem("sdrawcaB", {
  "score": 40,
  "threshold": 3,
  "weightmap": {
    "cyborg secrets": 2,
    "basic-asm": 1
  }
})
```

I would like to know if anyone has strong feelings on this.

**Comment by GroundPound** [comment]
Jonathan and I discussed this briefly. We agree that the intermixing of problem definitions with competition-specific definitions is a pain point. However, we do not feel that `config.py` is the right place for this information. I suggest a new `competition.json` (with a better name) that defines the placement and interaction of problems in an event. I recommend JSON because it really doesn't need to be arbitrary code and would make the creation of a problem linter easier.

Jonathan felt particularly strongly that for whatever solution is adopted that this information can only be defined in one place. That is, you either have to define it in the `problem.json` or through `configure_problem`.

**Comment by royragsdale** [comment]
Closed as a legacy enhancement and development shifting to [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform).

Most of this is addressed in [picoCTF-shell-manager](https://github.com/picoCTF/picoCTF-shell-manage) with the concept of a bundle.
