### ISSUE TITLE
Vagrant Script Assumes /vagrant/

### ISSUE THREAD

**Issue by ManuelNM** [picoCTF/picoCTF-Platform-2#40]
In
https://github.com/picoCTF/picoCTF-Platform-2/blob/master/scripts/vagrant_setup.sh
Change line 35:
From:
cp /vagrant/config/ctf.nginx /etc/nginx/sites-enabled/ctf
To
cp /home/vagrant/config/ctf.nginx /etc/nginx/sites-enabled/ctf

**Comment by GroundPound** [comment]
I suspect you ran into this problem when you weren't using the Vagrant environment. When launched under Vagrant, the VM or the container has a mount to the repository via `/vagrant`. Since the primary purpose of `vagrant_setup.sh` is to support Vagrant I do not consider this a bug in the Vagrantfile. We should, however, be mindful of deployment scenarios outside Vagrant in our scripts or documentation. The current draft of the documentation in #39 implies that the script will work fine outside of Vagrant. I believe the documentation should be updated before merging. Does that sound reasonable @jburket ?

**Comment by royragsdale** [comment]
The merged documentation in #39 discusses the non vagrant setup user case.

Please see [GettingStarted.md](https://github.com/picoCTF/picoCTF-Platform-2/blob/4cd86daa3f42b1be3e613d53d2861dfe987894f6/GettingStarted.md)
