### ISSUE TITLE
Limit Attempts per Problem

### ISSUE THREAD

**Issue by bobacadodl** [picoCTF/picoCTF-Platform-2#47]
There should be some way to limit the amount of attempts a team is allowed on a problem, to prevent teams from attempting to brute force an answer

**Comment by royragsdale** [comment]
Hi @bobacadodl this is a great recommendation, however I am going to close this specific issue because we have transitioned development efforts to a new version of the [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform).

You can track progress on this enhancement in [Issue 31](https://github.com/picoCTF/picoCTF-web/issues/31) as well as in [Pull Request 44](https://github.com/picoCTF/picoCTF-web/pull/44).

I hope you check out the new platform as we have added a lot of nice functionality.
