### ISSUE TITLE
How can I disable hints?

### ISSUE THREAD

**Issue by sachinkamath** [picoCTF/picoCTF-Platform-2#52]
Is there any way that I can disable hints? Or maybe, make hints cost the participant a few points?

**Comment by royragsdale** [comment]
Hi @sachinkamath, this is idea we have discussed but is not something that is currently implemented. 

The simplest solution would be to remove the hint from each `problem.json` file.

Another more involved method if you wanted to completely remove hints from the user interface would be to modify [problems.html](https://github.com/picoCTF/picoCTF-Platform-2/blob/4cd86daa3f42b1be3e613d53d2861dfe987894f6/web/problems.html).

I understand neither are particularly elegant but the should do the trick in a pinch.

Since we have are focusing on developing the latest version of the [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform), I will close this issue here and move it over as an enhancement there.
